import '../../domain/entities/proxy_profile.dart';
import '../../domain/errors/app_error.dart';
import '../common/uri_utils.dart';

/// MasterDNSVPN (DNS-tunnel transport, MIT-licensed Go engine at GitHub
/// `masterking32 / MasterDnsVPN`) adapter.
///
/// Import formats:
///  * mdvpn://<base64url(toml)>#name           — exported config snippet
///  * raw client_config.toml text pasted/imported
///
/// Runtime: NEXUS generates the TOML + resolvers file, launches the external
/// `mdvpn` client (SOCKS5 mode) and exposes it through sing-box as an upstream
/// so TUN / system proxy / routing / chaining all work on top.
class MasterDnsVpnParser {
  ProxyProfile parseToml(String text, {String? name}) {
    final kv = <String, String>{};
    for (final line in text.split(RegExp(r'\r?\n'))) {
      final l = line.trim();
      if (l.isEmpty || l.startsWith('#') || l.startsWith('[')) continue;
      final idx = l.indexOf('=');
      if (idx <= 0) continue;
      var key = l.substring(0, idx).trim();
      var value = l.substring(idx + 1).trim();
      // TOML array form: DOMAINS = ["a.com", "b.com"]
      if (value.startsWith('[') && value.endsWith(']')) {
        value = value
            .substring(1, value.length - 1)
            .split(',')
            .map((e) => e.trim().replaceAll('"', ''))
            .where((e) => e.isNotEmpty)
            .join(',');
      } else if (value.startsWith('"') &&
          value.endsWith('"') &&
          value.length >= 2) {
        value = value.substring(1, value.length - 1);
      }
      kv[key.toUpperCase()] = value;
    }
    // v0.3.1: upstream schema uses DOMAINS (array); legacy used
    // SERVER_ADDRESS. First domain is the tunnel server host.
    final domains = (kv['DOMAINS'] ?? '')
        .split(',')
        .map((e) => e.trim())
        .where((e) => e.isNotEmpty)
        .toList();
    final server = domains.isNotEmpty
        ? domains.first
        : (kv['SERVER_ADDRESS'] ?? kv['SERVER_HOST'] ?? '');
    final port = int.tryParse(kv['SERVER_PORT'] ?? kv['UDP_PORT'] ?? '');
    if (server.isEmpty) {
      throw ParseError(
          'MasterDNSVPN configuration needs DOMAINS (or legacy SERVER_ADDRESS).',
          likelyCauses: ['Paste a complete client_config.toml from your provider'],
          raw: text);
    }
    final name0 = kv['NAME'] ?? 'MasterDNSVPN $server';
    // §2/§22: the shared key is a SECRET. Move it into `password` (which the
    // persistence layer vaultifies) and redact it from the stored raw TOML —
    // rawConfig otherwise persists plaintext in the JSON store.
    final secretKey = kv.remove('ENCRYPTION_KEY');
    var storedRaw = text;
    if (secretKey != null && secretKey.isNotEmpty) {
      storedRaw = text.split(RegExp(r'\r?\n')).map((line) {
        final t = line.trim();
        if (t.toUpperCase().startsWith('ENCRYPTION_KEY')) {
          return 'ENCRYPTION_KEY = "<redacted>"';
        }
        return line;
      }).join('\n');
    }
    return ProxyProfile(
      id: Ids.newId(),
      name: name0,
      server: server,
      port: port ?? 53,
      protocol: ProxyProtocol.masterDnsVpn,
      core: CoreKind.masterDnsVpn,
      password: (secretKey == null || secretKey.isEmpty) ? null : secretKey,
      rawParams: kv,
      rawConfig: storedRaw,
      source: ProfileSource.fileImport,
    );
  }

  ProxyProfile parseUri(String raw) {
    final uri = Uri.tryParse(raw);
    if (uri == null || uri.scheme != 'mdvpn') {
      throw ParseError('Not a MasterDNSVPN link.', raw: raw);
    }
    final b64 = uri.path.replaceFirst('/', '');
    final toml = UriUtils.tryDecodeBase64(b64);
    if (toml == null) {
      throw ParseError('MasterDNSVPN link payload is not valid.', raw: raw);
    }
    return parseToml(toml,
        name: UriUtils.stripFragment(uri.fragment));
  }

  /// Generates the client_config.toml consumed by the mdvpn engine
  /// (v0.3.1: upstream schema; key delivered via -k, never in this file).
  String generateToml(ProxyProfile p, {String? encryptionKey}) {
    final q = p.rawParams;
    String esc(String v) => v
        .replaceAll('\\', '\\\\')
        .replaceAll('"', '\\"')
        .replaceAll('\n', '\\n')
        .replaceAll('\r', '\\r')
        .replaceAll('\t', '\\t');
    final domains = (q['DOMAINS'] ?? '')
        .split(',')
        .map((e) => e.trim())
        .where((e) => e.isNotEmpty)
        .toList();
    if (domains.isEmpty) domains.add(p.server);
    final method = int.tryParse(q['DATA_ENCRYPTION_METHOD'] ?? '1') ?? 1;
    final b = StringBuffer()
      ..writeln('# Generated by Atlanhix — MasterDNSVPN client config')
      ..writeln(
          'DOMAINS = [${domains.map((d) => '"${esc(d)}"').join(', ')}]')
      ..writeln('DATA_ENCRYPTION_METHOD = $method')
      ..writeln('PROTOCOL_TYPE = "SOCKS5"')
      ..writeln('LISTEN_IP = "127.0.0.1"')
      ..writeln('LISTEN_PORT = ${q['SOCKS5_PORT'] ?? '18000'}')
      ..writeln('MTU = ${int.tryParse(q['MTU'] ?? '1230') ?? 1230}');
    final resolvers = (q['RESOLVERS'] ?? '')
        .split(',')
        .map((e) => e.trim())
        .where((e) => e.isNotEmpty)
        .toList();
    if (resolvers.isNotEmpty) {
      b.writeln(
          'RESOLVERS = [${resolvers.map((r) => '"${esc(r)}"').join(', ')}]');
    }
    return b.toString();
  }

  /// NEXUS-side share link (base64url of the TOML payload).
  String exportUri(ProxyProfile p) =>
      'mdvpn:///${UriUtils.encodeBase64Url(p.rawConfig ?? '')}'
      '#${Uri.encodeComponent(p.name)}';

  static bool looksLikeToml(String text) {
    final t = text.trimLeft();
    return t.startsWith('#') || RegExp(r'^[A-Z_]+\s*=', multiLine: true).hasMatch(t);
  }

  static List<Map<String, String>> parseResolverFile(String text) {
    // v0.3.1 upstream format: one resolver per line — `host`, `host:port`,
    // CIDR, or `[v6]:port`. (The previous space-separated parse was wrong.)
    final out = <Map<String, String>>[];
    for (final line in text.split(RegExp(r'\r?\n'))) {
      final l = line.trim();
      if (l.isEmpty || l.startsWith('#')) continue;
      String host;
      String port = '53';
      if (l.startsWith('[')) {
        // [2001:4860:4860::8888]:53
        final close = l.indexOf(']');
        if (close > 0) {
          host = l.substring(1, close);
          if (l.length > close + 2 && l[close + 1] == ':') {
            port = l.substring(close + 2);
          }
        } else {
          host = l;
        }
      } else if (l.contains(':') && !l.contains('::')) {
        final idx = l.lastIndexOf(':');
        host = l.substring(0, idx);
        port = l.substring(idx + 1);
      } else {
        host = l;
      }
      out.add({'host': host, 'port': port});
    }
    return out;
  }
}
