import '../../domain/entities/proxy_profile.dart';
import '../../domain/errors/app_error.dart';
import '../common/uri_utils.dart';

/// MasterDNSVPN (DNS-tunnel transport, MIT-licensed Go engine at GitHub
/// `masterking32 / MasterDnsVPN`) adapter.
///
/// Import formats:
///  * mdvpn://<base64url(toml)>#name           — exported config snippet
///  * raw client_config.toml text pasted/imported
///
/// Runtime: NEXUS generates the TOML + resolvers file, launches the external
/// `mdvpn` client (SOCKS5 mode) and exposes it through sing-box as an upstream
/// so TUN / system proxy / routing / chaining all work on top.
class MasterDnsVpnParser {
  ProxyProfile parseToml(String text, {String? name}) {
    final kv = <String, String>{};
    for (final line in text.split(RegExp(r'\r?\n'))) {
      final l = line.trim();
      if (l.isEmpty || l.startsWith('#') || l.startsWith('[')) continue;
      final idx = l.indexOf('=');
      if (idx <= 0) continue;
      var key = l.substring(0, idx).trim();
      var value = l.substring(idx + 1).trim();
      if (value.startsWith('"') && value.endsWith('"') && value.length >= 2) {
        value = value.substring(1, value.length - 1);
      }
      if (key.startsWith('USE_') || key.startsWith('DATA_') || key.startsWith('ENCRYPTION')) {
        key = key; // keep as-is, engine expects exact keys
      }
      kv[key.toUpperCase()] = value;
    }
    final server = kv['SERVER_ADDRESS'] ?? kv['SERVER_HOST'] ?? '';
    final port = int.tryParse(kv['SERVER_PORT'] ?? kv['UDP_PORT'] ?? '');
    if (server.isEmpty) {
      throw ParseError('MasterDNSVPN configuration needs SERVER_ADDRESS.',
          likelyCauses: ['Paste a complete client_config.toml from your provider'],
          raw: text);
    }
    return ProxyProfile(
      id: Ids.newId(),
      name: name ?? kv['NAME'] ?? 'MasterDNSVPN $server',
      server: server,
      port: port ?? 53,
      protocol: ProxyProtocol.masterDnsVpn,
      core: CoreKind.masterDnsVpn,
      rawParams: kv,
      rawConfig: text,
      source: ProfileSource.fileImport,
    );
  }

  ProxyProfile parseUri(String raw) {
    final uri = Uri.tryParse(raw);
    if (uri == null || uri.scheme != 'mdvpn') {
      throw ParseError('Not a MasterDNSVPN link.', raw: raw);
    }
    final b64 = uri.path.replaceFirst('/', '');
    final toml = UriUtils.tryDecodeBase64(b64);
    if (toml == null) {
      throw ParseError('MasterDNSVPN link payload is not valid.', raw: raw);
    }
    return parseToml(toml,
        name: UriUtils.stripFragment(uri.fragment));
  }

  /// Generates the client_config.toml consumed by the mdvpn engine.
  String generateToml(ProxyProfile p, {required String encryptionKeyPath}) {
    final q = p.rawParams;
    final resolvers = (q['RESOLVERS'] ?? '')
        .split(',')
        .map((e) => e.trim())
        .where((e) => e.isNotEmpty)
        .toList();
    final b = StringBuffer()
      ..writeln('# Generated by NEXUS — MasterDNSVPN client config')
      ..writeln('SERVER_ADDRESS = "${p.server}"')
      ..writeln('SERVER_PORT = "${p.port}"')
      ..writeln('SUBDOMAIN = "${q['SUBDOMAIN'] ?? ''}"')
      ..writeln('SERVER_PUBLIC_KEY = "${q['SERVER_PUBLIC_KEY'] ?? ''}"')
      ..writeln('DATA_ENCRYPTION_METHOD = "${q['DATA_ENCRYPTION_METHOD'] ?? '1'}"')
      ..writeln('ENCRYPTION_KEY_FILE = "$encryptionKeyPath"')
      ..writeln('USE_TUN_MODE = "false"')
      ..writeln('USE_EXTERNAL_SOCKS5 = "false"')
      ..writeln('SOCKS5_LISTEN_HOST = "127.0.0.1"')
      ..writeln('SOCKS5_LISTEN_PORT = "${q['SOCKS5_PORT'] ?? '9720'}"')
      ..writeln('MTU = "${q['MTU'] ?? '1230'}"');
    if (resolvers.isNotEmpty) {
      b.writeln('RESOLVERS = [${resolvers.map((r) => '"$r"').join(', ')}]');
    }
    return b.toString();
  }

  /// NEXUS-side share link (base64url of the TOML payload).
  String exportUri(ProxyProfile p) =>
      'mdvpn:///${UriUtils.encodeBase64Url(p.rawConfig ?? '')}'
      '#${Uri.encodeComponent(p.name)}';

  static bool looksLikeToml(String text) {
    final t = text.trimLeft();
    return t.startsWith('#') || RegExp(r'^[A-Z_]+\s*=', multiLine: true).hasMatch(t);
  }

  static List<Map<String, String>> parseResolverFile(String text) {
    // client_resolvers.simple: one resolver per line, "host port" or host.
    final out = <Map<String, String>>[];
    for (final line in text.split(RegExp(r'\r?\n'))) {
      final l = line.trim();
      if (l.isEmpty || l.startsWith('#')) continue;
      final parts = l.split(RegExp(r'\s+'));
      out.add({
        'host': parts[0],
        'port': parts.length > 1 ? parts[1] : '53',
      });
    }
    return out;
  }
}
