import 'dart:convert';

import 'package:flutter/services.dart';

import '../core/logger.dart';

/// v0.5.3 — Dart-side handle to the Android `:mihomo` process (see
/// AtlanhixMihomoChannel.kt). Mirrors [XrayBridge]: boot probe sets
/// [available]; start/stop carry the FULL mihomo config JSON generated by
/// MihomoConfigGenerator. Desktop is a MissingPluginException → the local
/// binary path is used instead (MihomoRuntime).
class MihomoBridge {
  MihomoBridge._();
  static final MihomoBridge instance = MihomoBridge._();

  static const _channel = MethodChannel('dev.atlanhix/mihomo');

  bool _statusKnown = false;

  // ignore: unused_field — kept for the future status readback API
  bool _running = false;

  // ignore: unused_field — kept for the future status readback API
  int _mixedPort = 0;

  /// True once the native side reports libmihomo.so is present in this
  /// build. False = honest "mihomo off" state.
  bool available = false;

  /// Boot handshake (called from main after runApp): asks the native side
  /// whether the binary exists. Safe on desktop (MissingPluginException).
  Future<void> probe() async {
    try {
      final raw = await _channel.invokeMethod<String>('status');
      if (raw == null) return;
      final j = jsonDecode(raw) as Map<String, dynamic>;
      available = j['available'] == true;
      _running = j['running'] == true;
      _mixedPort = (j['mixedPort'] as num?)?.toInt() ?? 0;
      _statusKnown = true;
    } on MissingPluginException {
      available = false; // desktop: the binary path is used instead
    } catch (_) {
      available = false;
    }
  }

  bool get statusKnown => _statusKnown;

  /// Start the engine with [configJson] (the FULL mihomo config). [port] is
  /// the mixed inbound the front tunnel dials (must match the config's
  /// `mixed-port`). Returns true when the native side accepted the start.
  Future<bool> start(String configJson, int port) async {
    try {
      final raw = await _channel.invokeMethod<String>('start', {
        'config': configJson,
        'mixedPort': port,
      });
      final j = jsonDecode(raw ?? '{}') as Map<String, dynamic>;
      final ok = j['ok'] == true;
      if (ok) {
        _running = true;
        _mixedPort = port;
      }
      return ok;
    } on MissingPluginException {
      return false; // desktop: MihomoRuntime owns the start
    } catch (e) {
      Logger.instance.warn('runtime',
          'mihomo start failed: ${Logger.redact(e.toString())}');
      return false;
    }
  }

  Future<void> stop() async {
    try {
      await _channel.invokeMethod<String>('stop');
    } on MissingPluginException {
      // desktop: MihomoRuntime owns the stop
    } catch (_) {}
    _running = false;
    _mixedPort = 0;
  }
}
